### ISSUE TITLE
Pytests failing

### ISSUE THREAD

**Issue by Kohulan** [hannbus/ChemIcal-DatasEt-comparatoR#22] opened 2022-09-02 12:21 UTC
Hi @hannbus ,

The pytests are failing according to the GitHub actions:

Please take a look at this error:
```
==================================== ERRORS ====================================
___________________ ERROR collecting Tests/test_functions.py ___________________
Tests/test_functions.py:7: in <module>
    testdict = cider.import_as_data_dict("unittest_data")
.tox/py310/lib/python3.10/site-packages/CIDER/cider.py:50: in import_as_data_dict
    for dict_name in os.listdir(data_dir):
E   FileNotFoundError: [Errno 2] No such file or directory: 'unittest_data'
=========================== short test summary info ============================
ERROR Tests/test_functions.py - FileNotFoundError: [Errno 2] No such file or ...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```
- Kohulan

**Comment by JonasSchaub** [comment] 2022-09-02 12:27
We have discussed this in the last meeting: The tests only work if the current working directory is in the test folder. Here, pytest is started in the repository root folder, I assume. We already put this on "Hannah's to do list" to define the paths in a way that they work indifferently of the current working directory.

**Comment by hannbus** [comment] 2022-09-05 06:43
Hi @Kohulan ,
please try again if pytest is still failing. For me it works even outside the test folder. If it is working for you as well we can close this issue, can't we?

**Comment by Kohulan** [comment] 2022-09-05 08:49
Hi @hannbus ,
The pytests are failing in our GitHub actions. please check that and if that gets resolved then we can close this issue.

**Comment by JonasSchaub** [comment] 2022-09-08 10:43
@hannbus on which branch/commit are the tests working "even outside the test folder" for you? The problem here is with the last commit of the main branch. Maybe this is creating confusion here.

**Comment by hannbus** [comment] 2022-09-09 08:02
The tests work in my branch. All paths definitions should be changed after the commit 5c49936, but the changes are not yet on the main branch and therefore the tests might fail there.
In general I only work on my branch, because I'm not sure when it is okay to push something to main.

**Comment by JonasSchaub** [comment] 2022-09-09 08:26
Usually, you would start a pull request of your branch into the main branch, your collaborators would review your changes, and -if they are approved- your request is accepted and your branch merged. 
Would you say that your recent work on your branch is ready for review?

**Comment by JonasSchaub** [comment] 2022-09-09 09:12
@hannbus for me, nine tests are also failing on the latest commit of your dev branch when I run pytest from the repository root dir *after deleting all the output folders*:

````
(ChemIcal_DatasEt_compaRator) D:\Project_molecule_set_comparisons\CIDER_Hannah_git>pytest
============================================================================= test session starts =============================================================================
platform win32 -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: D:\Project_molecule_set_comparisons\CIDER_Hannah_git, configfile: tox.ini
collected 28 items

Tests\test_functions.py ...F.....F.....FF...F...FFFF                                                                                                                     [100%]

================================================================================== FAILURES ===================================================================================
_____________________________________________________________________________ test_draw_molecules _____________________________________________________________________________

    def test_draw_molecules():
        cider.draw_molecules(testdict)
        # Assert that the picture is exported
        test_path = os.path.join(os.path.split(__file__)[0],
                                 "output", "mol_grid.png")
>       assert os.path.exists(test_path)
E       AssertionError: assert False
E        +  where False = <function exists at 0x0000026093226B90>('D:\\Project_molecule_set_comparisons\\CIDER_Hannah_git\\Tests\\output\\mol_grid.png')
E        +    where <function exists at 0x0000026093226B90> = <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'>.exists
E        +      where <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'> = os.path

Tests\test_functions.py:38: AssertionError
_________________________________________________________________________ test_visualize_intersection _________________________________________________________________________

    def test_visualize_intersection():
        cider.visualize_intersection(testdict)
        # Assert that the figure is exported
        test_path = os.path.join(os.path.split(__file__)[0],
                                 "output", "intersection.png")
>       assert os.path.exists(test_path)
E       AssertionError: assert False
E        +  where False = <function exists at 0x0000026093226B90>('D:\\Project_molecule_set_comparisons\\CIDER_Hannah_git\\Tests\\output\\intersection.png')
E        +    where <function exists at 0x0000026093226B90> = <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'>.exists
E        +      where <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'> = os.path

Tests\test_functions.py:166: AssertionError
________________________________________________________________________ test_discrete_descriptor_plot ________________________________________________________________________

    def test_discrete_descriptor_plot():
>       cider._discrete_descriptor_plot(testdict, "Number of H-Donors")

Tests\test_functions.py:233:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\CIDER\cider.py:643: in _discrete_descriptor_plot
    descriptor_plot = descriptor_df.plot(
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\pandas\plotting\_core.py:972: in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\pandas\plotting\_matplotlib\__init__.py:71: in plot
    plot_obj.generate()
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\pandas\plotting\_matplotlib\core.py:328: in generate
    self._setup_subplots()
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\pandas\plotting\_matplotlib\core.py:386: in _setup_subplots
    fig = self.plt.figure(figsize=self.figsize)
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\pyplot.py:787: in figure
    manager = new_figure_manager(
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\pyplot.py:306: in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\backend_bases.py:3494: in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\backends\_backend_tk.py:925: in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tkinter.Tk object .>, screenName = None, baseName = 'pytest', className = 'matplotlib', useTk = True, sync = False, use = None

    def __init__(self, screenName=None, baseName=None, className='Tk',
                 useTk=True, sync=False, use=None):
        """Return a new Toplevel widget on screen SCREENNAME. A new Tcl interpreter will
        be created. BASENAME will be used for the identification of the profile file (see
        readprofile).
        It is constructed from sys.argv[0] without extensions if None is given. CLASSNAME
        is the name of the widget class."""
        self.master = None
        self.children = {}
        self._tkloaded = False
        # to avoid recursions in the getattr code in case of failure, we
        # ensure that self.tk is always _something_.
        self.tk = None
        if baseName is None:
            import os
            baseName = os.path.basename(sys.argv[0])
            baseName, ext = os.path.splitext(baseName)
            if ext not in ('.py', '.pyc'):
                baseName = baseName + ext
        interactive = False
>       self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
E       _tkinter.TclError: Can't find a usable init.tcl in the following directories:
E           C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6 C:/Users/jonas/Anaconda/Anaconda3/envs/lib/tcl8.6 C:/Users/jonas/Anaconda/Anaconda3/lib/tcl8.6 C:/Users/jonas/Anaconda/Anaconda3/envs/library C:/Users/jonas/Anaconda/Anaconda3/library C:/Users/jonas/Anaconda/Anaconda3/tcl8.6.12/library C:/Users/jonas/Anaconda/tcl8.6.12/library
E
E       C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6/init.tcl: couldn't read file "C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6/init.tcl": No error
E       couldn't read file "C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6/init.tcl": No error
E           while executing
E       "source C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6/init.tcl"
E           ("uplevel" body line 1)
E           invoked from within
E       "uplevel #0 [list source $tclfile]"
E
E
E       This probably means that Tcl wasn't installed properly.

C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\tkinter\__init__.py:2299: TclError
_______________________________________________________________________ test_continuous_descriptor_plot _______________________________________________________________________

    def test_continuous_descriptor_plot():
        cider._continuous_descriptor_plot(testdict, "LogP")
        # Assert that the image and the table are exported
        test_path_logppng = os.path.join(os.path.split(__file__)[0],
                                         "output", "distribution_of_LogP.png")
        test_path_logpcsv = os.path.join(os.path.split(__file__)[0],
                                         "output", "table_LogP.csv")
>       assert os.path.exists(test_path_logppng)
E       AssertionError: assert False
E        +  where False = <function exists at 0x0000026093226B90>('D:\\Project_molecule_set_comparisons\\CIDER_Hannah_git\\Tests\\output\\distribution_of_LogP.png')
E        +    where <function exists at 0x0000026093226B90> = <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'>.exists
E        +      where <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'> = os.path

Tests\test_functions.py:253: AssertionError
_____________________________________________________________________________ test_lipinski_plot ______________________________________________________________________________

    def test_lipinski_plot():
        cider.lipinski_plot(testdict)
        # Assert that the picture is exported
        test_path = os.path.join(os.path.split(__file__)[0],
                                 "output", "lipinski_plot.png")
>       assert os.path.exists(test_path)
E       AssertionError: assert False
E        +  where False = <function exists at 0x0000026093226B90>('D:\\Project_molecule_set_comparisons\\CIDER_Hannah_git\\Tests\\output\\lipinski_plot.png')
E        +    where <function exists at 0x0000026093226B90> = <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'>.exists
E        +      where <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'> = os.path

Tests\test_functions.py:338: AssertionError
______________________________________________________________________ test_draw_most_frequent_scaffolds ______________________________________________________________________

    def test_draw_most_frequent_scaffolds():
        cider.draw_most_frequent_scaffolds(testdict)
        # Assert that the function generates new keys in the dictionary
        assert (
            any(
                key == cider.scaffold_list_keyname
                for key in list(testdict["set_A.sdf"].keys())
            )
        )
        assert (
            any(
                key == cider.scaffold_summary_keyname
                for key in list(testdict["set_A.sdf"].keys())
            )
        )
        # Assert that the picture is exported
        test_path = os.path.join(os.path.split(__file__)[0],
                                 "output", "scaffold_grid.png")
>       assert os.path.exists(test_path)
E       AssertionError: assert False
E        +  where False = <function exists at 0x0000026093226B90>('D:\\Project_molecule_set_comparisons\\CIDER_Hannah_git\\Tests\\output\\scaffold_grid.png')
E        +    where <function exists at 0x0000026093226B90> = <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'>.exists
E        +      where <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'> = os.path

Tests\test_functions.py:389: AssertionError
______________________________________________________________________ test_chemical_space_visualization ______________________________________________________________________

    def test_chemical_space_visualization():
        cider.chemical_space_visualization(testdict, interactive=False)
        # Assert that the picture is exported
        test_path = os.path.join(os.path.split(__file__)[0],
                                 "output", "chemical_space.png")
>       assert os.path.exists(test_path)
E       AssertionError: assert False
E        +  where False = <function exists at 0x0000026093226B90>('D:\\Project_molecule_set_comparisons\\CIDER_Hannah_git\\Tests\\output\\chemical_space.png')
E        +    where <function exists at 0x0000026093226B90> = <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'>.exists
E        +      where <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'> = os.path

Tests\test_functions.py:400: AssertionError
_______________________________________________________________________ test_export_single_dict_values ________________________________________________________________________

    def test_export_single_dict_values():
        cider.export_single_dict_values(testdict)
        # Assert that the picture is exported
        test_path_setA = os.path.join(os.path.split(__file__)[0],
                                      "output", "descriptor_values_set_A.csv")
        test_path_setB = os.path.join(os.path.split(__file__)[0],
                                      "output", "descriptor_values_set_B.csv")
        test_path_setD = os.path.join(os.path.split(__file__)[0],
                                      "output", "descriptor_values_set_D.csv")
>       assert os.path.exists(test_path_setA)
E       AssertionError: assert False
E        +  where False = <function exists at 0x0000026093226B90>('D:\\Project_molecule_set_comparisons\\CIDER_Hannah_git\\Tests\\output\\descriptor_values_set_A.csv')
E        +    where <function exists at 0x0000026093226B90> = <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'>.exists
E        +      where <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'> = os.path

Tests\test_functions.py:411: AssertionError
_________________________________________________________________________ test_export_all_figures_pdf _________________________________________________________________________

    def test_export_all_figures_pdf():
        cider.export_all_figures_pdf(testdict)
        # Assert that the picture is exported
        test_path = os.path.join(os.path.split(__file__)[0],
                                 "output", "all_figures.pdf")
>       assert os.path.exists(test_path)
E       AssertionError: assert False
E        +  where False = <function exists at 0x0000026093226B90>('D:\\Project_molecule_set_comparisons\\CIDER_Hannah_git\\Tests\\output\\all_figures.pdf')
E        +    where <function exists at 0x0000026093226B90> = <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'>.exists
E        +      where <module 'ntpath' from 'C:\\Users\\jonas\\Anaconda\\Anaconda3\\envs\\ChemIcal_DatasEt_compaRator\\lib\\ntpath.py'> = os.path

Tests\test_functions.py:420: AssertionError
=========================================================================== short test summary info ===========================================================================
FAILED Tests/test_functions.py::test_draw_molecules - AssertionError: assert False
FAILED Tests/test_functions.py::test_visualize_intersection - AssertionError: assert False
FAILED Tests/test_functions.py::test_discrete_descriptor_plot - _tkinter.TclError: Can't find a usable init.tcl in the following directories:
FAILED Tests/test_functions.py::test_continuous_descriptor_plot - AssertionError: assert False
FAILED Tests/test_functions.py::test_lipinski_plot - AssertionError: assert False
FAILED Tests/test_functions.py::test_draw_most_frequent_scaffolds - AssertionError: assert False
FAILED Tests/test_functions.py::test_chemical_space_visualization - AssertionError: assert False
FAILED Tests/test_functions.py::test_export_single_dict_values - AssertionError: assert False
FAILED Tests/test_functions.py::test_export_all_figures_pdf - AssertionError: assert False
======================================================================== 9 failed, 19 passed in 13.19s ========================================================================
````

When I run from the Tests folder, everything works:

````
(ChemIcal_DatasEt_compaRator) D:\Project_molecule_set_comparisons\CIDER_Hannah_git\Tests>pytest
============================================================================= test session starts =============================================================================
platform win32 -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: D:\Project_molecule_set_comparisons\CIDER_Hannah_git, configfile: tox.ini
collected 28 items

test_functions.py ............................                                                                                                                           [100%]

============================================================================= 28 passed in 10.47s =============================================================================
````

I guess the problem is that the test class is always looking for the output in the "Tests" folder while cider.py is always writing the an output folder in the current working directory. I see that you did not adjust the path definitions in cider.py as you did in test_functions.py (with ``test_path = os.path.join(os.path.split(__file__)[0], "output", "mol_grid.png")``), could this be the problem? 

Or maybe, you have to define in the paths of the test file that it should look in the repository root dir for the output. 

Or tell me if I did something wrong here.

On the plus side, the test class is finding its input data in both variants which is good (because it is the original problem of this issue)!

Hope this helps!
Jonas

**Comment by hannbus** [comment] 2022-09-12 08:17
Thanks @JonasSchaub , that was indeed helpful.
Now the output folder will always be created in the same directory as the folder with the SDFiles. The tests should work also when deleting the output folder (which I actually forgot last time). Maybe one of you can check if it actually works.

**Comment by Kohulan** [comment] 2022-09-12 08:23
Hi @hannbus ,
Thanks a lot :)
If you have fixed it then create a pull request so we can see whether tests are failing or not.

**Comment by JonasSchaub** [comment] 2022-09-12 08:34
Basically, the tests are running now (on the dev-Hannah branch), great!

I only have one weird problem: When I delete the output folders, one test is failing. But if I run the tests a second time, everything is fine. See output below:

````
(ChemIcal_DatasEt_compaRator) D:\Project_molecule_set_comparisons\CIDER_Hannah_git>pytest
================================================= test session starts =================================================
platform win32 -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: D:\Project_molecule_set_comparisons\CIDER_Hannah_git, configfile: tox.ini
collected 28 items

Tests\test_functions.py .........................F..                                                             [100%]

====================================================== FAILURES =======================================================
__________________________________________ test_chemical_space_visualization __________________________________________

    def test_chemical_space_visualization():
>       cider.chemical_space_visualization(testdict, interactive=False)

D:\Project_molecule_set_comparisons\CIDER_Hannah_git\Tests\test_functions.py:396:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\CIDER\cider.py:1196: in chemical_space_visualization
    chem_space.visualize_plot(filename="output/chemical_space")
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\chemplot\chemplot.py:442: in visualize_plot
    fig, ax = plt.subplots(figsize=(size,size))
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\pyplot.py:1434: in subplots
    fig = figure(**fig_kw)
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\pyplot.py:787: in figure
    manager = new_figure_manager(
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\pyplot.py:306: in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\backend_bases.py:3494: in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\site-packages\matplotlib\backends\_backend_tk.py:925: in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tkinter.Tk object .>, screenName = None, baseName = 'pytest', className = 'matplotlib', useTk = True
sync = False, use = None

    def __init__(self, screenName=None, baseName=None, className='Tk',
                 useTk=True, sync=False, use=None):
        """Return a new Toplevel widget on screen SCREENNAME. A new Tcl interpreter will
        be created. BASENAME will be used for the identification of the profile file (see
        readprofile).
        It is constructed from sys.argv[0] without extensions if None is given. CLASSNAME
        is the name of the widget class."""
        self.master = None
        self.children = {}
        self._tkloaded = False
        # to avoid recursions in the getattr code in case of failure, we
        # ensure that self.tk is always _something_.
        self.tk = None
        if baseName is None:
            import os
            baseName = os.path.basename(sys.argv[0])
            baseName, ext = os.path.splitext(baseName)
            if ext not in ('.py', '.pyc'):
                baseName = baseName + ext
        interactive = False
>       self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
E       _tkinter.TclError: Can't find a usable init.tcl in the following directories:
E           C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6 C:/Users/jonas/Anaconda/Anaconda3/envs/lib/tcl8.6 C:/Users/jonas/Anaconda/Anaconda3/lib/tcl8.6 C:/Users/jonas/Anaconda/Anaconda3/envs/library C:/Users/jonas/Anaconda/Anaconda3/library C:/Users/jonas/Anaconda/Anaconda3/tcl8.6.12/library C:/Users/jonas/Anaconda/tcl8.6.12/library
E
E       C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6/init.tcl: couldn't read file "C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6/init.tcl": No error
E       couldn't read file "C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6/init.tcl": No error
E           while executing
E       "source C:/Users/jonas/Anaconda/Anaconda3/envs/ChemIcal_DatasEt_compaRator/Library/lib/tcl8.6/init.tcl"
E           ("uplevel" body line 1)
E           invoked from within
E       "uplevel #0 [list source $tclfile]"
E
E
E       This probably means that Tcl wasn't installed properly.

C:\Users\jonas\Anaconda\Anaconda3\envs\ChemIcal_DatasEt_compaRator\lib\tkinter\__init__.py:2299: TclError
=============================================== short test summary info ===============================================
FAILED Tests/test_functions.py::test_chemical_space_visualization - _tkinter.TclError: Can't find a usable init.tcl i...
============================================ 1 failed, 27 passed in 21.41s ============================================

(ChemIcal_DatasEt_compaRator) D:\Project_molecule_set_comparisons\CIDER_Hannah_git>pytest
================================================= test session starts =================================================
platform win32 -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: D:\Project_molecule_set_comparisons\CIDER_Hannah_git, configfile: tox.ini
collected 28 items

Tests\test_functions.py ............................                                                             [100%]

================================================= 28 passed in 10.24s =================================================
````

Does anyone have an idea what the problem is in the first run?

**Comment by JonasSchaub** [comment] 2022-09-12 08:38
@hannbus can you do a pull request of your dev branch to the main branch as Kohulan suggested? Then, the automatic testing routines that we set up on GitHub will run on your code and we can see what it says.

**Comment by hannbus** [comment] 2022-09-12 08:53
I did a pull request from my branch to main.

I also got this Tcl error sometimes but usually it disappears when running the tests a second time (with deleting the old output).

**Comment by JonasSchaub** [comment] 2022-09-12 09:04
On the pull request, the automatic tests are still failing but it seems to be only an assertion error regarding the order of the imported SD files. Apparently, the automatic tests do not have the tcl problem. 

@hannbus could you adjust the assertion in the failing test?

**Comment by hannbus** [comment] 2022-09-12 12:04
I changed the unittest for the import and in the pull request it works now. But there is an error now due to the linter. This error is caused from the import of  IPythonConsole. This needs to be imported for the grid images but is not used anywhere so the linter raises an error.

**Comment by JonasSchaub** [comment] 2022-09-12 12:16
@hannbus , we saw that linter error, merged your pull request, and added this error to the tox file as ignored error on the main branch. The tests on the latest main commit should work now. Let's see.

**Comment by JonasSchaub** [comment] 2022-09-12 12:17
The tests are working now 🎉
We can close this issue now, right @Kohulan ?

**Closed** 2022-09-12 12:18 UTC
Labels: bug
